# definit les urls: quelle méthode du controller appeler par url
xbros_homepage:
    path:     /
    defaults: { _controller: XbrosBundle:Default:index }

xbros_resources:
    path:     /resources
    defaults: { _controller: XbrosBundle:Default:resources }

xbros_codingrules:
    path:     /coding-rules
    defaults: { _controller: XbrosBundle:Default:codingRules }

xbros_todo:
    path:     /todo
    defaults: { _controller: XbrosBundle:Default:todo }

xbros_system:
    path:     /system
    defaults: { _controller: XbrosBundle:Default:system }

xbros_adrien:
    path:     /adrien
    defaults: { _controller: XbrosBundle:Default:adrien }

xbros_simon:
    path:     /simon
    defaults: { _controller: XbrosBundle:Default:simon }

xbros_simonmusic:
    path:     /simon/music/{track}
    defaults:
        _controller: XbrosBundle:Default:simonMusic
        track:

xbros_projectrubik:
    path:     /project/rubik
    defaults: { _controller: XbrosBundle:Default:projectRubik }
