xbros_homepage:
    path:     /
    defaults: { _controller: XbrosBundle:Default:index }

xbros_resources:
    path:     /resources
    defaults: { _controller: XbrosBundle:Default:resources }

xbros_codingrules:
    path:     /coding-rules
    defaults: { _controller: XbrosBundle:Default:codingRules }